apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-app
  labels:
    app: ai-agent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent-app
  template:
    metadata:
      labels:
        app: ai-agent-app
    spec:
      containers:
      - name: ai-agent-app
        # This will be replaced with the actual ECR repository URL during deployment
        # Format: {aws_account_id}.dkr.ecr.{region}.amazonaws.com/{repository_name}:{tag}
        image: ${ECR_REPOSITORY_URL}:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10