apiVersion: v1
kind: Service
metadata:
  name: ai-agent-app-service
  labels:
    app: ai-agent-app
  annotations:
    # Optional: Add any service annotations if needed
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ai-agent-app