name: Deploy S3 Bucket to AWS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Select Terraform workspace
        run: terraform workspace select prod || terraform workspace new prod

      - name: Terraform Apply
        run: terraform apply -auto-approve
        
      # Get Terraform outputs
      - name: Get Terraform outputs
        id: terraform-outputs
        run: |
          echo "S3_BUCKET_NAME=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV

      # Run the deployment script
      - name: Deploy with environment-aware script
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
